#include <iostream>
#include <stdlib.h>
#include <time.h>
#include <random>
#include <functional>
using namespace std;

/*
int main()
{
    std::random_device rd;  //Will be used to obtain a seed for the random number engine
    std::mt19937 gen(rd()); //Standard mersenne_twister_engine seeded with rd()
    std::uniform_real_distribution<> dis(0, 109);
    for (int n = 0; n < 10; ++n) {
        // Use dis to transform the random unsigned int generated by gen into a 
        // double in [1, 2). Each call to dis(gen) generates a new random double
        std::cout << (int) dis(gen) << '\n';
    }
    std::cout << '\n';
}
*/

int main()
{
    std::default_random_engine gen;
    std::uniform_real_distribution<double> distribution(7500,7515);

    for (int i = 0; i < 3; i++)
    {
        cout << distribution(gen) << endl;
    }
}